### PR TITLE
feat: user profile image cropping

### PR DESCRIPTION
**Pull request by leMaur**
## Summary
https://app.clickup.com/t/jva6kk

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Review by alexbarnsley — CHANGES_REQUESTED** [review]
This might not be related to this PR, maybe the main msq PR, but when I upload a profile image and crop it, it requires a page reload before seeing the image. It works correctly on the Project Registration page

https://user-images.githubusercontent.com/8069294/121499633-7ac6d480-c9d5-11eb-8009-365776f22c06.mov

Also, this may be an issue with modals in general, if I click down to drag on the crop screen, move my mouse outside of the modal and release, it closes the modal

https://user-images.githubusercontent.com/8069294/121500050-dbeea800-c9d5-11eb-8a21-1b3c92475fbd.mov

**Comment by leMaur** [comment]
@alexbarnsley 
1. _when I upload a profile image and crop it, it requires a page reload before seeing the image._
The only solution that worked for me is to [dispatch a browser event](https://github.com/ArkEcosystem/laravel-fortify/pull/144/files#diff-86ca6f1a60b94cca2369d335f0078c91acfdd50dfd9bfcb0bced0652e28cf0f4R58), then [listen it on MSQ](https://github.com/ArkEcosystem/marketsquare.io/pull/2003/files#diff-2c4d46cf96d1123e38891913bba7e68ecd4363cb962850b6fd9d1b8b0483aba3R118).
2. _click down to drag on the crop screen, move my mouse outside of the modal and release, it closes the modal._
Maybe I can try to disable modal closing by clicking outside of it.

**Review by samharperpittam — CHANGES_REQUESTED** [review]
It looks like the page auto-refreshes for me when I upload a new Profile image, which causes any data in the fields to be cleared which could be incredibly annoying for any user that has completed their profile before uploading a profile image. 


https://user-images.githubusercontent.com/44671015/121505924-2888b200-c9db-11eb-9df4-ce49defc3651.mov

**Comment by leMaur** [comment]
@samharperpittam Nooo! I didnt' think about that :dizzy_face:. Let me find a solution...

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
