### PR TITLE
feat: use external link component for 2auth apps

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

https://app.clickup.com/t/g98tk2

Now it uses the external link component to show the links for the 2auth apps.

To test add this to msq and go to the security section on your account.

image
image

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Comment by ItsANameToo** [comment]
@alfonsobries we may need to move the `external-link` component to the UI lib 🤔

**Comment by alfonsobries** [comment]
> @alfonsobries we may need to move the `external-link` component to the UI lib 🤔

yep, I'm on it

**Comment by alfonsobries** [comment]
@ItsANameToo once this is merged https://github.com/ArkEcosystem/laravel-ui/pull/421 and updated here the test should be fixed.

**Comment by ItsANameToo** [comment]
2.36.0 contains it @alfonsobries

**Comment by alfonsobries** [comment]
@ItsANameToo 🎉✅

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
