### PR TITLE
refactor: use built-in password rule to validate passwords

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

https://app.clickup.com/t/tzbvvx

- Removes the old service we use to validate the password in favor of the built-in rule
- Add the new `uncompromised` rule (it is validated after form submit)

To test merge this on msq and test the password form (register form and update password form)

To test the uncompromised rule use the password `Passwords123!` 
image

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Comment by Highjhacker** [comment]
- `uncompromised` rule works, but only after I input both password & password confirmation, could it be shown as soon as the user filled the password field ? 

- probably a stupid question, but just to be sure to understand, is there any reason to not declare anything about the `uncompromised` rule in places such as https://github.com/ArkEcosystem/laravel-fortify/pull/150/files#diff-205f874c8b37b63058fd406b56732bd18f42f89b3b68c5ac95cb9a36632a590eR25 ? 

Other than that seems to works fine, but maybe we should add a new point in that check-list (as shown below), such as `Uncompromised password`, what do you guys think ? @alfonsobries @ItsANameToo

**Comment by alfonsobries** [comment]
@ItsANameToo @Highjhacker yeah adding the uncompromised rule to the list worth a discussion, personally think it feels odd maybe I can add that validation error only after submitting

**Comment by alfonsobries** [comment]
For the moment I just updated msq to only validate the password confirmation when that field is changed, meaning the   "Uncompromised password" error will only appear only after the form is submitted 

In my opinion, that's ok, another checkmark for that specific rule may look odd, and it's not easy to find a leaked password with our current rules

@ItsANameToo @Highjhacker

**Comment by Highjhacker** [comment]
Just tried it and can confirm that it's properly shown after submitting the form. Imo it's good too, clear enough, so more about @ItsANameToo preferences on that one :hmhm:

**Review by Highjhacker — APPROVED** [review]

**Comment by ItsANameToo** [comment]
shouldn't be added to the checklist, it won't apply to majority of users and serves more as an additional check than a password requirement

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
